version: '3.8'

services:
  backend:
    build: ./backend

  frontend:
    build: ./frontend
    ports:
      - "8282:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306